### PR TITLE
Innovation hours PR

### PR DESCRIPTION
**Pull request by maliavka**
* added basic example component that uses styled-component and decorators
* ensured it's compiled by ws
* used this example in already existing basic spa
* fixed bug with publicPath while running yarn watch (alias to webpack-serve)

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
Thanks. Can you fix the test in `packages/example-spa-ts/tests/unit.tsx` (see CI)? I'll have a look at the other code changes tomorrow ✌️

**Comment by akvamalin** [comment]
@donaldpipowitch Thanks for support. CI should be clear now.

**Comment by donaldpipowitch** [comment]
I'll merge this now and add the proposed changes myself. I'd like to update to Babel 7 and it would be nice to have this example to check if everything still works 👍

**Comment by maliavka** [comment]
Ok, thank you.

**Pull request merged**
